<?php

declare(strict_types=1);

use Gildsmith\Contract\Product\AttributeInterface;
use Gildsmith\Contract\Product\AttributeValueInterface;
use Gildsmith\Contract\Product\BlueprintInterface;
use Gildsmith\Contract\Product\ProductCollectionInterface;
use Gildsmith\Contract\Product\ProductInterface;
use Gildsmith\Contract\Routing\ResourceAbility as Ability;
use Gildsmith\Product\Controllers\Attribute\AttributeCreateController;
use Gildsmith\Product\Controllers\Attribute\AttributeDeleteController;
use Gildsmith\Product\Controllers\Attribute\AttributeFindController;
use Gildsmith\Product\Controllers\Attribute\AttributeIndexController;
use Gildsmith\Product\Controllers\Attribute\AttributeRestoreController;
use Gildsmith\Product\Controllers\Attribute\AttributeTrashController;
use Gildsmith\Product\Controllers\Attribute\AttributeTrashedController;
use Gildsmith\Product\Controllers\Attribute\AttributeUpdateController;
use Gildsmith\Product\Controllers\AttributeValue\AttributeValueCreateController;
use Gildsmith\Product\Controllers\AttributeValue\AttributeValueDeleteController;
use Gildsmith\Product\Controllers\AttributeValue\AttributeValueFindController;
use Gildsmith\Product\Controllers\AttributeValue\AttributeValueIndexController;
use Gildsmith\Product\Controllers\AttributeValue\AttributeValueRestoreController;
use Gildsmith\Product\Controllers\AttributeValue\AttributeValueTrashController;
use Gildsmith\Product\Controllers\AttributeValue\AttributeValueTrashedController;
use Gildsmith\Product\Controllers\AttributeValue\AttributeValueUpdateController;
use Gildsmith\Product\Controllers\Blueprint\BlueprintCreateController;
use Gildsmith\Product\Controllers\Blueprint\BlueprintDeleteController;
use Gildsmith\Product\Controllers\Blueprint\BlueprintFindController;
use Gildsmith\Product\Controllers\Blueprint\BlueprintIndexController;
use Gildsmith\Product\Controllers\Blueprint\BlueprintRestoreController;
use Gildsmith\Product\Controllers\Blueprint\BlueprintTrashController;
use Gildsmith\Product\Controllers\Blueprint\BlueprintTrashedController;
use Gildsmith\Product\Controllers\Blueprint\BlueprintUpdateController;
use Gildsmith\Product\Controllers\BlueprintAttribute\BlueprintAttributeAttachController;
use Gildsmith\Product\Controllers\BlueprintAttribute\BlueprintAttributeDetachController;
use Gildsmith\Product\Controllers\BlueprintAttribute\BlueprintAttributeIndexController;
use Gildsmith\Product\Controllers\BlueprintAttribute\BlueprintAttributeUpdateController;
use Gildsmith\Product\Controllers\Product\ProductCreateController;
use Gildsmith\Product\Controllers\Product\ProductDeleteController;
use Gildsmith\Product\Controllers\Product\ProductFindController;
use Gildsmith\Product\Controllers\Product\ProductIndexController;
use Gildsmith\Product\Controllers\Product\ProductRestoreController;
use Gildsmith\Product\Controllers\Product\ProductTrashController;
use Gildsmith\Product\Controllers\Product\ProductTrashedController;
use Gildsmith\Product\Controllers\Product\ProductUpdateController;
use Gildsmith\Product\Controllers\ProductCollection\ProductCollectionCreateController;
use Gildsmith\Product\Controllers\ProductCollection\ProductCollectionDeleteController;
use Gildsmith\Product\Controllers\ProductCollection\ProductCollectionFindController;
use Gildsmith\Product\Controllers\ProductCollection\ProductCollectionIndexController;
use Gildsmith\Product\Controllers\ProductCollection\ProductCollectionRestoreController;
use Gildsmith\Product\Controllers\ProductCollection\ProductCollectionTrashController;
use Gildsmith\Product\Controllers\ProductCollection\ProductCollectionTrashedController;
use Gildsmith\Product\Controllers\ProductCollection\ProductCollectionUpdateController;
use Illuminate\Support\Facades\Route;

Route::get('/products', ProductIndexController::class)->can(Ability::ViewAny->value, ProductInterface::class);
Route::post('/products', ProductCreateController::class)->can(Ability::Create->value, ProductInterface::class);
Route::get('/products/trashed', ProductTrashedController::class)->can(Ability::ViewTrashed->value, ProductInterface::class);
Route::post('/products/{code}/trash', ProductTrashController::class)->can(Ability::Trash->value, ProductInterface::class);
Route::post('/products/{code}/restore', ProductRestoreController::class)->can(Ability::Restore->value, ProductInterface::class);
Route::get('/products/{code}', ProductFindController::class)->can(Ability::View->value, ProductInterface::class);
Route::put('/products/{code}', ProductUpdateController::class)->can(Ability::Update->value, ProductInterface::class);
Route::patch('/products/{code}', ProductUpdateController::class)->can(Ability::Update->value, ProductInterface::class);
Route::delete('/products/{code}', ProductDeleteController::class)->can(Ability::Delete->value, ProductInterface::class);

Route::get('/attributes', AttributeIndexController::class)->can(Ability::ViewAny->value, AttributeInterface::class);
Route::post('/attributes', AttributeCreateController::class)->can(Ability::Create->value, AttributeInterface::class);
Route::get('/attributes/trashed', AttributeTrashedController::class)->can(Ability::ViewTrashed->value, AttributeInterface::class);
Route::post('/attributes/{code}/trash', AttributeTrashController::class)->can(Ability::Trash->value, AttributeInterface::class);
Route::post('/attributes/{code}/restore', AttributeRestoreController::class)->can(Ability::Restore->value, AttributeInterface::class);
Route::get('/attributes/{code}', AttributeFindController::class)->can(Ability::View->value, AttributeInterface::class);
Route::put('/attributes/{code}', AttributeUpdateController::class)->can(Ability::Update->value, AttributeInterface::class);
Route::patch('/attributes/{code}', AttributeUpdateController::class)->can(Ability::Update->value, AttributeInterface::class);
Route::delete('/attributes/{code}', AttributeDeleteController::class)->can(Ability::Delete->value, AttributeInterface::class);

Route::get('/attributes/{attribute}/values', AttributeValueIndexController::class)->can(Ability::ViewAny->value, AttributeValueInterface::class);
Route::post('/attributes/{attribute}/values', AttributeValueCreateController::class)->can(Ability::Create->value, AttributeValueInterface::class);
Route::get('/attributes/{attribute}/values/trashed', AttributeValueTrashedController::class)->can(Ability::ViewTrashed->value, AttributeValueInterface::class);
Route::post('/attributes/{attribute}/values/{value}/trash', AttributeValueTrashController::class)->can(Ability::Trash->value, AttributeValueInterface::class);
Route::post('/attributes/{attribute}/values/{value}/restore', AttributeValueRestoreController::class)->can(Ability::Restore->value, AttributeValueInterface::class);
Route::get('/attributes/{attribute}/values/{value}', AttributeValueFindController::class)->can(Ability::View->value, AttributeValueInterface::class);
Route::put('/attributes/{attribute}/values/{value}', AttributeValueUpdateController::class)->can(Ability::Update->value, AttributeValueInterface::class);
Route::patch('/attributes/{attribute}/values/{value}', AttributeValueUpdateController::class)->can(Ability::Update->value, AttributeValueInterface::class);
Route::delete('/attributes/{attribute}/values/{value}', AttributeValueDeleteController::class)->can(Ability::Delete->value, AttributeValueInterface::class);

Route::get('/blueprints', BlueprintIndexController::class)->can(Ability::ViewAny->value, BlueprintInterface::class);
Route::post('/blueprints', BlueprintCreateController::class)->can(Ability::Create->value, BlueprintInterface::class);
Route::get('/blueprints/trashed', BlueprintTrashedController::class)->can(Ability::ViewTrashed->value, BlueprintInterface::class);
Route::post('/blueprints/{code}/trash', BlueprintTrashController::class)->can(Ability::Trash->value, BlueprintInterface::class);
Route::post('/blueprints/{code}/restore', BlueprintRestoreController::class)->can(Ability::Restore->value, BlueprintInterface::class);
Route::get('/blueprints/{code}', BlueprintFindController::class)->can(Ability::View->value, BlueprintInterface::class);
Route::put('/blueprints/{code}', BlueprintUpdateController::class)->can(Ability::Update->value, BlueprintInterface::class);
Route::patch('/blueprints/{code}', BlueprintUpdateController::class)->can(Ability::Update->value, BlueprintInterface::class);
Route::delete('/blueprints/{code}', BlueprintDeleteController::class)->can(Ability::Delete->value, BlueprintInterface::class);

Route::get('/blueprints/{code}/attributes', BlueprintAttributeIndexController::class)->can(Ability::View->value, BlueprintInterface::class);
Route::post('/blueprints/{code}/attributes/{attribute}', BlueprintAttributeAttachController::class)->can(Ability::Update->value, BlueprintInterface::class);
Route::patch('/blueprints/{code}/attributes/{attribute}', BlueprintAttributeUpdateController::class)->can(Ability::Update->value, BlueprintInterface::class);
Route::delete('/blueprints/{code}/attributes/{attribute}', BlueprintAttributeDetachController::class)->can(Ability::Update->value, BlueprintInterface::class);

Route::get('/collections', ProductCollectionIndexController::class)->can(Ability::ViewAny->value, ProductCollectionInterface::class);
Route::post('/collections', ProductCollectionCreateController::class)->can(Ability::Create->value, ProductCollectionInterface::class);
Route::get('/collections/trashed', ProductCollectionTrashedController::class)->can(Ability::ViewTrashed->value, ProductCollectionInterface::class);
Route::post('/collections/{code}/trash', ProductCollectionTrashController::class)->can(Ability::Trash->value, ProductCollectionInterface::class);
Route::post('/collections/{code}/restore', ProductCollectionRestoreController::class)->can(Ability::Restore->value, ProductCollectionInterface::class);
Route::get('/collections/{code}', ProductCollectionFindController::class)->can(Ability::View->value, ProductCollectionInterface::class);
Route::put('/collections/{code}', ProductCollectionUpdateController::class)->can(Ability::Update->value, ProductCollectionInterface::class);
Route::patch('/collections/{code}', ProductCollectionUpdateController::class)->can(Ability::Update->value, ProductCollectionInterface::class);
Route::delete('/collections/{code}', ProductCollectionDeleteController::class)->can(Ability::Delete->value, ProductCollectionInterface::class);
